---
name: "Go Linter"
permissions:
  contents: "read"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci-lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"

      - uses: "actions/setup-go@v6"
        with:
          go-version: "stable"

      - uses: "golangci/golangci-lint-action@v9"
        with:
          version: "latest"
...
