---
name: "Go Vulnerability"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  govulncheck:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "golang/govulncheck-action@v1"
        with:
          go-package: "./..."
...
