---
name: "Go Vulnerability"
permissions:
  contents: "read"
  security-events: "write"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  govulncheck:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "golang/govulncheck-action@v1"
        with:
          go-package: "./..."
          output-format: "sarif"
          output-file: "results.sarif"

      - uses: "github/codeql-action/upload-sarif@v2"
        with:
          sarif_file: "results.sarif"
...
